### ISSUE TITLE
This thing is a horrid

### ISSUE THREAD

**Issue by Porkechebure** [alissadb/chatbot_llm#1]
Windows user.
https://medium.com/@alissabr/run-your-own-llm-powered-chatbot-in-5-easy-steps-8e5c0518f1b5
Trying to follow up this thing is a horrendous clusterfuck of cli hacks and infinite troubles.
This crap doesn't work and no one should ever follow it.

Pyenv needs hacks to be installed on windows and ton of workarounds.

Bah....

**Comment by alissadb** [comment]
I'm sorry to hear that. I haven't tested this on Windows, so I didn't know it was difficult to install Pyenv. Only on a Mac, with that it should work fine.
